using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using DataAccessLayer.Entities;
using Microsoft.EntityFrameworkCore;

namespace DataAccessLayer
{
    public class CurrencyContext : DbContext
    {
        public CurrencyContext()
        {
        }
        public CurrencyContext(DbContextOptions options) : base(options)
        {
        }

        public DbSet<Currency> Currencies { get; set; }
        public DbSet<ExchangeRate> ExchangeRates { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Currency>()
                .HasMany(x => x.ExchangeRates)
                .WithOne()
                .IsRequired();
            modelBuilder.Entity<Currency>().HasKey(x => x.Id);
            modelBuilder.Entity<Currency>().HasIndex(x => x.Code).IsUnique();
            modelBuilder.Entity<Currency>().HasData(GetCurrencies());
            modelBuilder.Entity<ExchangeRate>().HasData(GetExchangeRates());
        }

        #region Seed
        //данные взяты с сайта https://www.banki.ru/products/currency/cb/
        private static readonly Dictionary<string, Guid> currencyIds = new Dictionary<string, Guid>
        {
            {"USD", Guid.NewGuid()},
            {"EUR", Guid.NewGuid()},
            {"AUD", Guid.NewGuid()},
            {"AZN", Guid.NewGuid()},
            {"AMD", Guid.NewGuid()},
            {"BYN", Guid.NewGuid()},
            {"BGN", Guid.NewGuid()},
            {"BRL", Guid.NewGuid()},
            {"HUF", Guid.NewGuid()},
            {"KRW", Guid.NewGuid()},
            {"HKD", Guid.NewGuid()},
            {"DKK", Guid.NewGuid()},
            {"INR", Guid.NewGuid()},
            {"KZT", Guid.NewGuid()},
            {"CAD", Guid.NewGuid()},
            {"KGS", Guid.NewGuid()},
            {"CNY", Guid.NewGuid()},
            {"MDL", Guid.NewGuid()},
            {"RON", Guid.NewGuid()},
            {"TMT", Guid.NewGuid()},
            {"NOK", Guid.NewGuid()},
            {"PLN", Guid.NewGuid()},
            {"SGD", Guid.NewGuid()},
            {"TJS", Guid.NewGuid()},
            {"TRY", Guid.NewGuid()},
            {"UZS", Guid.NewGuid()},
            {"UAH", Guid.NewGuid()},
            {"GBP", Guid.NewGuid()},
            {"CZK", Guid.NewGuid()},
            {"SEK", Guid.NewGuid()},
            {"CHF", Guid.NewGuid()},
            {"ZAR", Guid.NewGuid()},
            {"JPY", Guid.NewGuid()}
        };
        private static IEnumerable<Currency> GetCurrencies()
        {
            return new[]
            {
                new Currency {Id = currencyIds["USD"], Code = "USD", Name = "Доллар США"},
                new Currency {Id = currencyIds["EUR"], Code = "EUR", Name = "Евро"},
                new Currency {Id = currencyIds["AUD"], Code = "AUD", Name = "Австралийский доллар"},
                new Currency {Id = currencyIds["AZN"], Code = "AZN", Name = "Азебайджанский манат"},
                new Currency {Id = currencyIds["AMD"], Code = "AMD", Name = "Армянский драм"},
                new Currency {Id = currencyIds["BYN"], Code = "BYN", Name = "Белорусский рубль"},
                new Currency {Id = currencyIds["BGN"], Code = "BGN", Name = "Болгарский лев"},
                new Currency {Id = currencyIds["BRL"], Code = "BRL", Name = "Бразильский реал"},
                new Currency {Id = currencyIds["HUF"], Code = "HUF", Name = "Венгерский форинт"},
                new Currency {Id = currencyIds["KRW"], Code = "KRW", Name = "Вона Республики Корея"},
                new Currency {Id = currencyIds["HKD"], Code = "HKD", Name = "Гонконгский доллар"},
                new Currency {Id = currencyIds["DKK"], Code = "DKK", Name = "Датская крона"},
                new Currency {Id = currencyIds["INR"], Code = "INR", Name = "Индийская рупия"},
                new Currency {Id = currencyIds["KZT"], Code = "KZT", Name = "Казахсканский тенге"},
                new Currency {Id = currencyIds["CAD"], Code = "CAD", Name = "Канадский доллар"},
                new Currency {Id = currencyIds["KGS"], Code = "KGS", Name = "Киргизский сом"},
                new Currency {Id = currencyIds["CNY"], Code = "CNY", Name = "Китайский юань"},
                new Currency {Id = currencyIds["MDL"], Code = "MDL", Name = "Молдавский лей"},
                new Currency {Id = currencyIds["RON"], Code = "RON", Name = "Новый румынский лей"},
                new Currency {Id = currencyIds["TMT"], Code = "TMT", Name = "Новый туркменский манат"},
                new Currency {Id = currencyIds["NOK"], Code = "NOK", Name = "Норвежская крона"},
                new Currency {Id = currencyIds["PLN"], Code = "PLN", Name = "Польский злотый"},
                new Currency {Id = currencyIds["SGD"], Code = "SGD", Name = "Сингапурский доллар"},
                new Currency {Id = currencyIds["TJS"], Code = "TJS", Name = "Таджикский сомони"},
                new Currency {Id = currencyIds["TRY"], Code = "TRY", Name = "Турецкая лира"},
                new Currency {Id = currencyIds["UZS"], Code = "UZS", Name = "Узбекский сум"},
                new Currency {Id = currencyIds["UAH"], Code = "UAH", Name = "Украинская гривна"},
                new Currency {Id = currencyIds["GBP"], Code = "GBP", Name = "Фунт стерлингов Соединенного королевства"},
                new Currency {Id = currencyIds["CZK"], Code = "CZK", Name = "Чешская крона"},
                new Currency {Id = currencyIds["SEK"], Code = "SEK", Name = "Шведская крона"},
                new Currency {Id = currencyIds["CHF"], Code = "CHF", Name = "Швейцарский франк"},
                new Currency {Id = currencyIds["ZAR"], Code = "ZAR", Name = "Южноафриканский рэнд"},
                new Currency {Id = currencyIds["JPY"], Code = "JPY", Name = "Японская иена"}
            };
        }

        private static IEnumerable<ExchangeRate> GetExchangeRates()
        {
            return new[]
            {
                //12.10.20
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["USD"], Date = Convert.ToDateTime("2020-10-12"), Rate = 77.0284f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["EUR"], Date = Convert.ToDateTime("2020-10-12"), Rate = 90.7163f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AUD"], Date = Convert.ToDateTime("2020-10-12"), Rate = 55.3603f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AZN"], Date = Convert.ToDateTime("2020-10-12"), Rate = 45.3375f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["AMD"], Date = Convert.ToDateTime("2020-10-12"), Rate = 15.7073f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BYN"], Date = Convert.ToDateTime("2020-10-12"), Rate = 29.6491f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BGN"], Date = Convert.ToDateTime("2020-10-12"), Rate = 46.4418f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BRL"], Date = Convert.ToDateTime("2020-10-12"), Rate = 13.7551f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["HUF"], Date = Convert.ToDateTime("2020-10-12"), Rate = 25.4656f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1000, CurrencyId = currencyIds["KRW"], Date = Convert.ToDateTime("2020-10-12"), Rate = 67.2485f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["HKD"], Date = Convert.ToDateTime("2020-10-12"), Rate = 99.3902f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["DKK"], Date = Convert.ToDateTime("2020-10-12"), Rate = 12.2048f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["INR"], Date = Convert.ToDateTime("2020-10-12"), Rate = 10.5332f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KZT"], Date = Convert.ToDateTime("2020-10-12"), Rate = 18.0209f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CAD"], Date = Convert.ToDateTime("2020-10-12"), Rate = 58.4967f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KGS"], Date = Convert.ToDateTime("2020-10-12"), Rate = 96.7160f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CNY"], Date = Convert.ToDateTime("2020-10-12"), Rate = 11.4728f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["MDL"], Date = Convert.ToDateTime("2020-10-12"), Rate = 45.4915f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["RON"], Date = Convert.ToDateTime("2020-10-12"), Rate = 18.6442f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["TMT"], Date = Convert.ToDateTime("2020-10-12"), Rate = 22.0396f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["NOK"], Date = Convert.ToDateTime("2020-10-12"), Rate = 83.3731f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["PLN"], Date = Convert.ToDateTime("2020-10-12"), Rate = 20.3134f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["SGD"], Date = Convert.ToDateTime("2020-10-12"), Rate = 56.7972f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TJS"], Date = Convert.ToDateTime("2020-10-12"), Rate = 74.6399f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TRY"], Date = Convert.ToDateTime("2020-10-12"), Rate = 97.1171f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10000, CurrencyId = currencyIds["UZS"], Date = Convert.ToDateTime("2020-10-12"), Rate = 74.4164f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["UAH"], Date = Convert.ToDateTime("2020-10-12"), Rate = 27.3005f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["GBP"], Date = Convert.ToDateTime("2020-10-12"), Rate = 99.7056f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["CZK"], Date = Convert.ToDateTime("2020-10-12"), Rate = 33.4593f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["SEK"], Date = Convert.ToDateTime("2020-10-12"), Rate = 87.0338f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CHF"], Date = Convert.ToDateTime("2020-10-12"), Rate = 84.2854f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["ZAR"], Date = Convert.ToDateTime("2020-10-12"), Rate = 46.7726f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["JPY"], Date = Convert.ToDateTime("2020-10-12"), Rate = 72.7575f},
                //13.10.20
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["USD"], Date = Convert.ToDateTime("2020-10-13"), Rate = 77.0239f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["EUR"], Date = Convert.ToDateTime("2020-10-13"), Rate = 91.0037f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AUD"], Date = Convert.ToDateTime("2020-10-13"), Rate = 55.6806f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AZN"], Date = Convert.ToDateTime("2020-10-13"), Rate = 45.3348f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["AMD"], Date = Convert.ToDateTime("2020-10-13"), Rate = 15.6887f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BYN"], Date = Convert.ToDateTime("2020-10-13"), Rate = 29.9961f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BGN"], Date = Convert.ToDateTime("2020-10-13"), Rate = 46.5148f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BRL"], Date = Convert.ToDateTime("2020-10-13"), Rate = 13.9241f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["HUF"], Date = Convert.ToDateTime("2020-10-13"), Rate = 25.5477f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1000, CurrencyId = currencyIds["KRW"], Date = Convert.ToDateTime("2020-10-13"), Rate = 67.0697f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["HKD"], Date = Convert.ToDateTime("2020-10-13"), Rate = 99.3844f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["DKK"], Date = Convert.ToDateTime("2020-10-13"), Rate = 12.2237f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["INR"], Date = Convert.ToDateTime("2020-10-13"), Rate = 10.5151f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KZT"], Date = Convert.ToDateTime("2020-10-13"), Rate = 17.9946f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CAD"], Date = Convert.ToDateTime("2020-10-13"), Rate = 58.6759f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KGS"], Date = Convert.ToDateTime("2020-10-13"), Rate = 96.7104f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CNY"], Date = Convert.ToDateTime("2020-10-13"), Rate = 11.4304f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["MDL"], Date = Convert.ToDateTime("2020-10-13"), Rate = 45.4687f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["RON"], Date = Convert.ToDateTime("2020-10-13"), Rate = 18.6720f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["TMT"], Date = Convert.ToDateTime("2020-10-13"), Rate = 22.0383f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["NOK"], Date = Convert.ToDateTime("2020-10-13"), Rate = 84.3894f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["PLN"], Date = Convert.ToDateTime("2020-10-13"), Rate = 20.3342f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["SGD"], Date = Convert.ToDateTime("2020-10-13"), Rate = 56.8400f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TJS"], Date = Convert.ToDateTime("2020-10-13"), Rate = 74.6356f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TRY"], Date = Convert.ToDateTime("2020-10-13"), Rate = 97.6073f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10000, CurrencyId = currencyIds["UZS"], Date = Convert.ToDateTime("2020-10-13"), Rate = 74.4120f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["UAH"], Date = Convert.ToDateTime("2020-10-13"), Rate = 27.2741f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["GBP"], Date = Convert.ToDateTime("2020-10-13"), Rate = 100.3621f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["CZK"], Date = Convert.ToDateTime("2020-10-13"), Rate = 33.5880f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["SEK"], Date = Convert.ToDateTime("2020-10-13"), Rate = 87.5909f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CHF"], Date = Convert.ToDateTime("2020-10-13"), Rate = 84.5209f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["ZAR"], Date = Convert.ToDateTime("2020-10-13"), Rate = 46.6806f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["JPY"], Date = Convert.ToDateTime("2020-10-13"), Rate = 72.9497f},
                //14.10.20
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["USD"], Date = Convert.ToDateTime("2020-10-14"), Rate = 77.2855f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["EUR"], Date = Convert.ToDateTime("2020-10-14"), Rate = 91.0732f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AUD"], Date = Convert.ToDateTime("2020-10-14"), Rate = 55.5837f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AZN"], Date = Convert.ToDateTime("2020-10-14"), Rate = 45.4888f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["AMD"], Date = Convert.ToDateTime("2020-10-14"), Rate = 15.7597f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BYN"], Date = Convert.ToDateTime("2020-10-14"), Rate = 30.0815f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BGN"], Date = Convert.ToDateTime("2020-10-14"), Rate = 46.5856f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BRL"], Date = Convert.ToDateTime("2020-10-14"), Rate = 13.9714f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["HUF"], Date = Convert.ToDateTime("2020-10-14"), Rate = 25.3945f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1000, CurrencyId = currencyIds["KRW"], Date = Convert.ToDateTime("2020-10-14"), Rate = 67.4173f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["HKD"], Date = Convert.ToDateTime("2020-10-14"), Rate = 99.7219f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["DKK"], Date = Convert.ToDateTime("2020-10-14"), Rate = 12.2434f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["INR"], Date = Convert.ToDateTime("2020-10-14"), Rate = 10.5398f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KZT"], Date = Convert.ToDateTime("2020-10-14"), Rate = 18.0052f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CAD"], Date = Convert.ToDateTime("2020-10-14"), Rate = 58.9156f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KGS"], Date = Convert.ToDateTime("2020-10-14"), Rate = 97.0388f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CNY"], Date = Convert.ToDateTime("2020-10-14"), Rate = 11.4672f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["MDL"], Date = Convert.ToDateTime("2020-10-14"), Rate = 45.5962f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["RON"], Date = Convert.ToDateTime("2020-10-14"), Rate = 18.6942f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["TMT"], Date = Convert.ToDateTime("2020-10-14"), Rate = 22.1132f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["NOK"], Date = Convert.ToDateTime("2020-10-14"), Rate = 84.3452f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["PLN"], Date = Convert.ToDateTime("2020-10-14"), Rate = 20.3581f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["SGD"], Date = Convert.ToDateTime("2020-10-14"), Rate = 56.8987f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TJS"], Date = Convert.ToDateTime("2020-10-14"), Rate = 74.7804f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TRY"], Date = Convert.ToDateTime("2020-10-14"), Rate = 97.7258f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10000, CurrencyId = currencyIds["UZS"], Date = Convert.ToDateTime("2020-10-14"), Rate = 74.6648f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["UAH"], Date = Convert.ToDateTime("2020-10-14"), Rate = 27.2902f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["GBP"], Date = Convert.ToDateTime("2020-10-14"), Rate = 100.7416f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["CZK"], Date = Convert.ToDateTime("2020-10-14"), Rate = 33.3185f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["SEK"], Date = Convert.ToDateTime("2020-10-14"), Rate = 87.8494f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CHF"], Date = Convert.ToDateTime("2020-10-14"), Rate = 84.9105f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["ZAR"], Date = Convert.ToDateTime("2020-10-14"), Rate = 46.7889f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["JPY"], Date = Convert.ToDateTime("2020-10-14"), Rate = 73.2703f},
                //15.10.20
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["USD"], Date = Convert.ToDateTime("2020-10-15"), Rate = 77.2759f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["EUR"], Date = Convert.ToDateTime("2020-10-15"), Rate = 90.7065f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AUD"], Date = Convert.ToDateTime("2020-10-15"), Rate = 55.4609f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AZN"], Date = Convert.ToDateTime("2020-10-15"), Rate = 45.4832f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["AMD"], Date = Convert.ToDateTime("2020-10-15"), Rate = 15.7545f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BYN"], Date = Convert.ToDateTime("2020-10-15"), Rate = 30.0439f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BGN"], Date = Convert.ToDateTime("2020-10-15"), Rate = 46.4036f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BRL"], Date = Convert.ToDateTime("2020-10-15"), Rate = 13.8733f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["HUF"], Date = Convert.ToDateTime("2020-10-15"), Rate = 24.9293f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1000, CurrencyId = currencyIds["KRW"], Date = Convert.ToDateTime("2020-10-15"), Rate = 67.4934f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["HKD"], Date = Convert.ToDateTime("2020-10-15"), Rate = 99.7096f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["DKK"], Date = Convert.ToDateTime("2020-10-15"), Rate = 12.1946f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["INR"], Date = Convert.ToDateTime("2020-10-15"), Rate = 10.5462f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KZT"], Date = Convert.ToDateTime("2020-10-15"), Rate = 17.9988f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CAD"], Date = Convert.ToDateTime("2020-10-15"), Rate = 58.8679f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KGS"], Date = Convert.ToDateTime("2020-10-15"), Rate = 96.9766f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CNY"], Date = Convert.ToDateTime("2020-10-15"), Rate = 11.4675f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["MDL"], Date = Convert.ToDateTime("2020-10-15"), Rate = 45.6444f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["RON"], Date = Convert.ToDateTime("2020-10-15"), Rate = 18.6153f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["TMT"], Date = Convert.ToDateTime("2020-10-15"), Rate = 22.1104f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["NOK"], Date = Convert.ToDateTime("2020-10-15"), Rate = 83.6944f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["PLN"], Date = Convert.ToDateTime("2020-10-15"), Rate = 20.2039f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["SGD"], Date = Convert.ToDateTime("2020-10-15"), Rate = 56.9000f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TJS"], Date = Convert.ToDateTime("2020-10-15"), Rate = 74.7711f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TRY"], Date = Convert.ToDateTime("2020-10-15"), Rate = 97.2305f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10000, CurrencyId = currencyIds["UZS"], Date = Convert.ToDateTime("2020-10-15"), Rate = 74.6555f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["UAH"], Date = Convert.ToDateTime("2020-10-15"), Rate = 27.2674f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["GBP"], Date = Convert.ToDateTime("2020-10-15"), Rate = 99.6859f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["CZK"], Date = Convert.ToDateTime("2020-10-15"), Rate = 33.1116f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["SEK"], Date = Convert.ToDateTime("2020-10-15"), Rate = 87.6760f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CHF"], Date = Convert.ToDateTime("2020-10-15"), Rate = 84.5654f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["ZAR"], Date = Convert.ToDateTime("2020-10-15"), Rate = 46.7905f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["JPY"], Date = Convert.ToDateTime("2020-10-15"), Rate = 73.3133f},
                //16.10.20
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["USD"], Date = Convert.ToDateTime("2020-10-16"), Rate = 77.9461f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["EUR"], Date = Convert.ToDateTime("2020-10-16"), Rate = 91.4542f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AUD"], Date = Convert.ToDateTime("2020-10-16"), Rate = 55.2248f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AZN"], Date = Convert.ToDateTime("2020-10-16"), Rate = 45.8776f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["AMD"], Date = Convert.ToDateTime("2020-10-16"), Rate = 15.8640f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BYN"], Date = Convert.ToDateTime("2020-10-16"), Rate = 30.2833f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BGN"], Date = Convert.ToDateTime("2020-10-16"), Rate = 46.6939f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BRL"], Date = Convert.ToDateTime("2020-10-16"), Rate = 13.9384f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["HUF"], Date = Convert.ToDateTime("2020-10-16"), Rate = 24.9992f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1000, CurrencyId = currencyIds["KRW"], Date = Convert.ToDateTime("2020-10-16"), Rate = 68.0033f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["HKD"], Date = Convert.ToDateTime("2020-10-16"), Rate = 10.0574f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["DKK"], Date = Convert.ToDateTime("2020-10-16"), Rate = 12.2698f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["INR"], Date = Convert.ToDateTime("2020-10-16"), Rate = 10.6223f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KZT"], Date = Convert.ToDateTime("2020-10-16"), Rate = 18.1824f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CAD"], Date = Convert.ToDateTime("2020-10-16"), Rate = 59.1576f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KGS"], Date = Convert.ToDateTime("2020-10-16"), Rate = 97.7889f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CNY"], Date = Convert.ToDateTime("2020-10-16"), Rate = 11.5803f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["MDL"], Date = Convert.ToDateTime("2020-10-16"), Rate = 45.9859f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["RON"], Date = Convert.ToDateTime("2020-10-16"), Rate = 18.7267f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["TMT"], Date = Convert.ToDateTime("2020-10-16"), Rate = 22.3022f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["NOK"], Date = Convert.ToDateTime("2020-10-16"), Rate = 83.3666f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["PLN"], Date = Convert.ToDateTime("2020-10-16"), Rate = 20.0778f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["SGD"], Date = Convert.ToDateTime("2020-10-16"), Rate = 57.3260f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TJS"], Date = Convert.ToDateTime("2020-10-16"), Rate = 75.4195f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TRY"], Date = Convert.ToDateTime("2020-10-16"), Rate = 98.2122f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10000, CurrencyId = currencyIds["UZS"], Date = Convert.ToDateTime("2020-10-16"), Rate = 75.3030f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["UAH"], Date = Convert.ToDateTime("2020-10-16"), Rate = 27.5049f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["GBP"], Date = Convert.ToDateTime("2020-10-16"), Rate = 101.1584f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["CZK"], Date = Convert.ToDateTime("2020-10-16"), Rate = 33.4676f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["SEK"], Date = Convert.ToDateTime("2020-10-16"), Rate = 87.8009f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CHF"], Date = Convert.ToDateTime("2020-10-16"), Rate = 85.2429f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["ZAR"], Date = Convert.ToDateTime("2020-10-16"), Rate = 46.7822f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["JPY"], Date = Convert.ToDateTime("2020-10-16"), Rate = 74.0616f},
                //17.10.20
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["USD"], Date = Convert.ToDateTime("2020-10-17"), Rate = 77.9644f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["EUR"], Date = Convert.ToDateTime("2020-10-17"), Rate = 91.3041f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AUD"], Date = Convert.ToDateTime("2020-10-17"), Rate = 55.2534f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["AZN"], Date = Convert.ToDateTime("2020-10-17"), Rate = 45.8884f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["AMD"], Date = Convert.ToDateTime("2020-10-17"), Rate = 15.8567f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BYN"], Date = Convert.ToDateTime("2020-10-17"), Rate = 30.3234f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BGN"], Date = Convert.ToDateTime("2020-10-17"), Rate = 46.6965f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["BRL"], Date = Convert.ToDateTime("2020-10-17"), Rate = 13.8912f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["HUF"], Date = Convert.ToDateTime("2020-10-17"), Rate = 25.0295f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1000, CurrencyId = currencyIds["KRW"], Date = Convert.ToDateTime("2020-10-17"), Rate = 68.0903f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["HKD"], Date = Convert.ToDateTime("2020-10-17"), Rate = 10.0598f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["DKK"], Date = Convert.ToDateTime("2020-10-17"), Rate = 12.2707f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["INR"], Date = Convert.ToDateTime("2020-10-17"), Rate = 10.6291f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KZT"], Date = Convert.ToDateTime("2020-10-17"), Rate = 18.1697f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CAD"], Date = Convert.ToDateTime("2020-10-17"), Rate = 59.0237f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["KGS"], Date = Convert.ToDateTime("2020-10-17"), Rate = 97.4555f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CNY"], Date = Convert.ToDateTime("2020-10-17"), Rate = 11.6398f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["MDL"], Date = Convert.ToDateTime("2020-10-17"), Rate = 45.8749f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["RON"], Date = Convert.ToDateTime("2020-10-17"), Rate = 18.7302f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["TMT"], Date = Convert.ToDateTime("2020-10-17"), Rate = 22.3074f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["NOK"], Date = Convert.ToDateTime("2020-10-17"), Rate = 83.2846f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["PLN"], Date = Convert.ToDateTime("2020-10-17"), Rate = 20.0345f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["SGD"], Date = Convert.ToDateTime("2020-10-17"), Rate = 57.3943f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TJS"], Date = Convert.ToDateTime("2020-10-17"), Rate = 75.4373f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["TRY"], Date = Convert.ToDateTime("2020-10-17"), Rate = 98.3468f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10000, CurrencyId = currencyIds["UZS"], Date = Convert.ToDateTime("2020-10-17"), Rate = 75.3206f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["UAH"], Date = Convert.ToDateTime("2020-10-17"), Rate = 27.4958f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["GBP"], Date = Convert.ToDateTime("2020-10-17"), Rate = 100.8625f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["CZK"], Date = Convert.ToDateTime("2020-10-17"), Rate = 33.4324f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["SEK"], Date = Convert.ToDateTime("2020-10-17"), Rate = 88.1541f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 1, CurrencyId = currencyIds["CHF"], Date = Convert.ToDateTime("2020-10-17"), Rate = 85.2163f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 10, CurrencyId = currencyIds["ZAR"], Date = Convert.ToDateTime("2020-10-17"), Rate = 47.0629f},
                new ExchangeRate {Id = Guid.NewGuid(),  UnitsNumber = 100, CurrencyId = currencyIds["JPY"], Date = Convert.ToDateTime("2020-10-17"), Rate = 74.0895f}
            };
        }
        #endregion
    }
}
