// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    partial class CurrencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("DataAccessLayer.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11bbbf0e-148a-45ca-b329-6c95864f1945"),
                            Code = "USD",
                            Name = "Доллар США"
                        },
                        new
                        {
                            Id = new Guid("bf9242d7-1f47-462b-8609-02588ec24072"),
                            Code = "EUR",
                            Name = "Евро"
                        },
                        new
                        {
                            Id = new Guid("a5d82e53-8aad-4978-a487-99f9368008c7"),
                            Code = "AUD",
                            Name = "Австралийский доллар"
                        },
                        new
                        {
                            Id = new Guid("119c0396-3fd0-418b-8ba0-2dda0cd98891"),
                            Code = "AZN",
                            Name = "Азебайджанский манат"
                        },
                        new
                        {
                            Id = new Guid("f0756449-1c50-40cc-ab55-b031e3ce9258"),
                            Code = "AMD",
                            Name = "Армянский драм"
                        },
                        new
                        {
                            Id = new Guid("f1b53bf2-c36b-403a-b96e-3f70b90a6dbd"),
                            Code = "BYN",
                            Name = "Белорусский рубль"
                        },
                        new
                        {
                            Id = new Guid("91dac2a6-21be-49cf-a420-6e9d34e0c283"),
                            Code = "BGN",
                            Name = "Болгарский лев"
                        },
                        new
                        {
                            Id = new Guid("2401357a-e357-4d9b-8f58-6f0ef018df23"),
                            Code = "BRL",
                            Name = "Бразильский реал"
                        },
                        new
                        {
                            Id = new Guid("565429b9-b082-43ae-a19f-962e9983a93d"),
                            Code = "HUF",
                            Name = "Венгерский форинт"
                        },
                        new
                        {
                            Id = new Guid("0d02d2f7-9d33-4170-affc-e4f109ba77d3"),
                            Code = "KRW",
                            Name = "Вона Республики Корея"
                        },
                        new
                        {
                            Id = new Guid("77018082-91cf-4237-a9f1-b8ea8e12d005"),
                            Code = "HKD",
                            Name = "Гонконгский доллар"
                        },
                        new
                        {
                            Id = new Guid("ead32013-ea79-4f7d-904f-74fe92e6a06d"),
                            Code = "DKK",
                            Name = "Датская крона"
                        },
                        new
                        {
                            Id = new Guid("966fa871-b850-48d0-b35a-01ac50ab133d"),
                            Code = "INR",
                            Name = "Индийская рупия"
                        },
                        new
                        {
                            Id = new Guid("75796b33-0cb2-465f-a2f9-b6b3174fdd6c"),
                            Code = "KZT",
                            Name = "Казахсканский тенге"
                        },
                        new
                        {
                            Id = new Guid("8082345e-6d29-4f64-8137-e0e3e3338f6e"),
                            Code = "CAD",
                            Name = "Канадский доллар"
                        },
                        new
                        {
                            Id = new Guid("cb62c5e7-7d50-4095-989d-ec7bbddb103d"),
                            Code = "KGS",
                            Name = "Киргизский сом"
                        },
                        new
                        {
                            Id = new Guid("3b4eaabf-996d-4e3d-b3dc-3c47dab4601c"),
                            Code = "CNY",
                            Name = "Китайский юань"
                        },
                        new
                        {
                            Id = new Guid("81b49f97-1846-4b89-a0af-1b9174f9c6ff"),
                            Code = "MDL",
                            Name = "Молдавский лей"
                        },
                        new
                        {
                            Id = new Guid("ba68a7cb-b46f-44a5-9048-de67b458c783"),
                            Code = "RON",
                            Name = "Новый румынский лей"
                        },
                        new
                        {
                            Id = new Guid("f5340578-affe-460e-a59a-cfbd87898a8e"),
                            Code = "TMT",
                            Name = "Новый туркменский манат"
                        },
                        new
                        {
                            Id = new Guid("24ad525f-049c-4f4d-981e-d35bc1a34ad5"),
                            Code = "NOK",
                            Name = "Норвежская крона"
                        },
                        new
                        {
                            Id = new Guid("ad43ed5e-95cb-4a02-9dfb-0023042a0fa3"),
                            Code = "PLN",
                            Name = "Польский злотый"
                        },
                        new
                        {
                            Id = new Guid("821abd50-4fe7-489b-88ac-798db01056a4"),
                            Code = "SGD",
                            Name = "Сингапурский доллар"
                        },
                        new
                        {
                            Id = new Guid("0d0c13aa-21df-46a5-bf47-a1851c7f5edf"),
                            Code = "TJS",
                            Name = "Таджикский сомони"
                        },
                        new
                        {
                            Id = new Guid("3c3aabcf-f99d-4c5b-83a5-26ab411aec8e"),
                            Code = "TRY",
                            Name = "Турецкая лира"
                        },
                        new
                        {
                            Id = new Guid("53371f01-e292-4357-99b5-a67d6736aac5"),
                            Code = "UZS",
                            Name = "Узбекский сум"
                        },
                        new
                        {
                            Id = new Guid("7df2afa7-c1c9-48d4-8e3c-dfbc7e7352ad"),
                            Code = "UAH",
                            Name = "Украинская гривна"
                        },
                        new
                        {
                            Id = new Guid("f0812695-d5a8-4bfb-91bf-85516f1c8812"),
                            Code = "GBP",
                            Name = "Фунт стерлингов Соединенного королевства"
                        },
                        new
                        {
                            Id = new Guid("9a0fcaf6-fd89-45c5-80c7-69667ecfc072"),
                            Code = "CZK",
                            Name = "Чешская крона"
                        },
                        new
                        {
                            Id = new Guid("9993e5ac-983c-41ce-9f1b-256146728aee"),
                            Code = "SEK",
                            Name = "Шведская крона"
                        },
                        new
                        {
                            Id = new Guid("2ca026ca-1fb4-42d1-81f1-d9b1f28fa5a7"),
                            Code = "CHF",
                            Name = "Швейцарский франк"
                        },
                        new
                        {
                            Id = new Guid("9bd76064-5329-4e9f-9099-539771740eff"),
                            Code = "ZAR",
                            Name = "Южноафриканский рэнд"
                        },
                        new
                        {
                            Id = new Guid("9e0e348d-167d-4a5d-b110-182f96ddc6f6"),
                            Code = "JPY",
                            Name = "Японская иена"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL");

                    b.Property<int>("UnitsNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("ExchangeRates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13e06473-0e00-48d9-b151-6de470646edd"),
                            CurrencyId = new Guid("11bbbf0e-148a-45ca-b329-6c95864f1945"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 77.0284f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("869a7fc3-23a9-42a4-b989-37233340667c"),
                            CurrencyId = new Guid("bf9242d7-1f47-462b-8609-02588ec24072"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 90.7163f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("0243770c-8057-4530-9f2a-e2d0439ee012"),
                            CurrencyId = new Guid("a5d82e53-8aad-4978-a487-99f9368008c7"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 55.3603f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("03692b9b-1675-4cc6-b87a-0c4856dfcb90"),
                            CurrencyId = new Guid("119c0396-3fd0-418b-8ba0-2dda0cd98891"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.3375f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("02823689-fab9-4f08-a984-48d7daa72e6e"),
                            CurrencyId = new Guid("f0756449-1c50-40cc-ab55-b031e3ce9258"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 15.7073f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("a08f20b0-488f-4bcc-a320-da4c42dddaf4"),
                            CurrencyId = new Guid("f1b53bf2-c36b-403a-b96e-3f70b90a6dbd"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 29.6491f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("9c90432d-9f04-40ff-a1b3-96d0df8823fa"),
                            CurrencyId = new Guid("91dac2a6-21be-49cf-a420-6e9d34e0c283"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.4418f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("1bcb88a5-dcaf-477f-9ecf-d5db7339a6ce"),
                            CurrencyId = new Guid("2401357a-e357-4d9b-8f58-6f0ef018df23"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 13.7551f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f1b301e8-a812-4870-b667-130569d4a2a0"),
                            CurrencyId = new Guid("565429b9-b082-43ae-a19f-962e9983a93d"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 25.4656f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("ce9d5173-bcd8-43f1-8b75-4ceca01c45b4"),
                            CurrencyId = new Guid("0d02d2f7-9d33-4170-affc-e4f109ba77d3"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 67.2485f,
                            UnitsNumber = 1000
                        },
                        new
                        {
                            Id = new Guid("f5647889-8366-44cd-bb7e-e6606b546687"),
                            CurrencyId = new Guid("77018082-91cf-4237-a9f1-b8ea8e12d005"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 99.3902f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("e2670483-a017-496f-b5b4-83c5766f863e"),
                            CurrencyId = new Guid("ead32013-ea79-4f7d-904f-74fe92e6a06d"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 12.2048f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("cbdcc8a3-0eba-4a89-997a-a4e84e2bc6c1"),
                            CurrencyId = new Guid("966fa871-b850-48d0-b35a-01ac50ab133d"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 10.5332f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("67564b10-07c5-44b3-8a6c-e1d1970059db"),
                            CurrencyId = new Guid("75796b33-0cb2-465f-a2f9-b6b3174fdd6c"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.0209f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("38fc40ce-f76e-4d7e-b5a7-8ef47af70b65"),
                            CurrencyId = new Guid("8082345e-6d29-4f64-8137-e0e3e3338f6e"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 58.4967f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("4c965d9a-4df7-4082-b151-42d4a52841f2"),
                            CurrencyId = new Guid("cb62c5e7-7d50-4095-989d-ec7bbddb103d"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 96.716f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("10262a80-d1ef-4b31-bd7a-9473f49ecf39"),
                            CurrencyId = new Guid("3b4eaabf-996d-4e3d-b3dc-3c47dab4601c"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 11.4728f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d0b94dde-2b07-4fed-9c58-75aa13f0ab67"),
                            CurrencyId = new Guid("81b49f97-1846-4b89-a0af-1b9174f9c6ff"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.4915f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("0f958a0a-0d2e-42a7-bff4-23d06a1a066f"),
                            CurrencyId = new Guid("ba68a7cb-b46f-44a5-9048-de67b458c783"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.6442f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("c553f1e4-4efd-49e3-83f4-d73c4d0b9750"),
                            CurrencyId = new Guid("f5340578-affe-460e-a59a-cfbd87898a8e"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 22.0396f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("8b276241-cd64-4978-a2a0-ad269f8145a5"),
                            CurrencyId = new Guid("24ad525f-049c-4f4d-981e-d35bc1a34ad5"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 83.3731f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("575a52d3-1ca7-4338-8e1e-8d58ca9b4a8e"),
                            CurrencyId = new Guid("ad43ed5e-95cb-4a02-9dfb-0023042a0fa3"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 20.3134f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("cf83c9ab-8ecc-42d5-ba0c-404c7683c496"),
                            CurrencyId = new Guid("821abd50-4fe7-489b-88ac-798db01056a4"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 56.7972f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("db4f6135-51f0-4597-aafe-2ece654104d2"),
                            CurrencyId = new Guid("0d0c13aa-21df-46a5-bf47-a1851c7f5edf"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.6399f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("afcf009e-4501-45f5-8d02-bbeaf9f3ec6b"),
                            CurrencyId = new Guid("3c3aabcf-f99d-4c5b-83a5-26ab411aec8e"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 97.1171f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("47d98a8c-b789-47b6-ac22-21892dd6b0ae"),
                            CurrencyId = new Guid("53371f01-e292-4357-99b5-a67d6736aac5"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.4164f,
                            UnitsNumber = 10000
                        },
                        new
                        {
                            Id = new Guid("b23c5225-fde6-4a37-ad48-0dd8b3a6c239"),
                            CurrencyId = new Guid("7df2afa7-c1c9-48d4-8e3c-dfbc7e7352ad"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 27.3005f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("da825a90-42d6-434b-8bc3-eb61e4c03c82"),
                            CurrencyId = new Guid("f0812695-d5a8-4bfb-91bf-85516f1c8812"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 99.7056f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("c70d4c1a-a435-49e3-ba89-dfbf511e8e6a"),
                            CurrencyId = new Guid("9a0fcaf6-fd89-45c5-80c7-69667ecfc072"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 33.4593f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("d84e2082-0ce4-4945-a8f0-0e4678028da2"),
                            CurrencyId = new Guid("9993e5ac-983c-41ce-9f1b-256146728aee"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 87.0338f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("03b86232-1904-4493-9db5-a5568c1dd16a"),
                            CurrencyId = new Guid("2ca026ca-1fb4-42d1-81f1-d9b1f28fa5a7"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 84.2854f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("0debf68d-f9e7-4952-b04c-4d1f390283d1"),
                            CurrencyId = new Guid("9bd76064-5329-4e9f-9099-539771740eff"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.7726f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("1a26a601-b92e-4ac4-90e9-21f6463231fe"),
                            CurrencyId = new Guid("9e0e348d-167d-4a5d-b110-182f96ddc6f6"),
                            Date = new DateTime(2020, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 72.7575f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("c1ec5e43-008c-4242-a09a-becd23ea7945"),
                            CurrencyId = new Guid("11bbbf0e-148a-45ca-b329-6c95864f1945"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 77.0239f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f68ffa63-6fdb-4152-8aef-29334e84d1d1"),
                            CurrencyId = new Guid("bf9242d7-1f47-462b-8609-02588ec24072"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 91.0037f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f222ef39-fcaa-4d91-96b5-e2346bfab610"),
                            CurrencyId = new Guid("a5d82e53-8aad-4978-a487-99f9368008c7"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 55.6806f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("94870102-05f0-4b44-8c6a-0f24450c462f"),
                            CurrencyId = new Guid("119c0396-3fd0-418b-8ba0-2dda0cd98891"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.3348f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b256afd7-831e-48df-93a6-a149962a663c"),
                            CurrencyId = new Guid("f0756449-1c50-40cc-ab55-b031e3ce9258"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 15.6887f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("0e9abf1a-51c2-41e5-964e-51fbd7ac9f10"),
                            CurrencyId = new Guid("f1b53bf2-c36b-403a-b96e-3f70b90a6dbd"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 29.9961f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f654eef8-f3ee-4ac1-a24d-e7d0d4731d70"),
                            CurrencyId = new Guid("91dac2a6-21be-49cf-a420-6e9d34e0c283"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.5148f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("e2c31f4a-6723-4e9c-8fd3-32f6b41cd500"),
                            CurrencyId = new Guid("2401357a-e357-4d9b-8f58-6f0ef018df23"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 13.9241f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("7a51fbe8-7915-46a2-a487-5d472b7392e1"),
                            CurrencyId = new Guid("565429b9-b082-43ae-a19f-962e9983a93d"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 25.5477f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("43a71601-9d4c-4f68-96df-7c8417a02465"),
                            CurrencyId = new Guid("0d02d2f7-9d33-4170-affc-e4f109ba77d3"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 67.0697f,
                            UnitsNumber = 1000
                        },
                        new
                        {
                            Id = new Guid("4783fc42-6e1b-4104-a282-0bf14fff5cd8"),
                            CurrencyId = new Guid("77018082-91cf-4237-a9f1-b8ea8e12d005"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 99.3844f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("a25a776d-4402-4638-a5e0-68b99886b70a"),
                            CurrencyId = new Guid("ead32013-ea79-4f7d-904f-74fe92e6a06d"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 12.2237f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("556f2cab-7f40-4f86-9fba-0b70d42e4ebf"),
                            CurrencyId = new Guid("966fa871-b850-48d0-b35a-01ac50ab133d"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 10.5151f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("ef688641-bacb-4341-baa4-ab3a3f102715"),
                            CurrencyId = new Guid("75796b33-0cb2-465f-a2f9-b6b3174fdd6c"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 17.9946f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("2e509334-fa7d-4893-b509-ce1f1191bc0e"),
                            CurrencyId = new Guid("8082345e-6d29-4f64-8137-e0e3e3338f6e"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 58.6759f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("ce2cb3df-bb32-477b-9b79-b42379784d71"),
                            CurrencyId = new Guid("cb62c5e7-7d50-4095-989d-ec7bbddb103d"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 96.7104f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("3941602c-ba00-4618-a27f-8eedc95f5997"),
                            CurrencyId = new Guid("3b4eaabf-996d-4e3d-b3dc-3c47dab4601c"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 11.4304f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("9637b852-bfbe-4cfb-be43-c06ebd4b9d5f"),
                            CurrencyId = new Guid("81b49f97-1846-4b89-a0af-1b9174f9c6ff"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.4687f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("837ad3a3-4bd2-419b-abdb-709a5eca8571"),
                            CurrencyId = new Guid("ba68a7cb-b46f-44a5-9048-de67b458c783"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.672f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("fd3f1b51-bbaf-44bc-a1d3-dd0ff7afe562"),
                            CurrencyId = new Guid("f5340578-affe-460e-a59a-cfbd87898a8e"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 22.0383f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("27d4ba7b-61b7-40fc-b315-4fba87746535"),
                            CurrencyId = new Guid("24ad525f-049c-4f4d-981e-d35bc1a34ad5"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 84.3894f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("f7fe1fb5-6b91-4dcc-a5c5-199ce46eb4ac"),
                            CurrencyId = new Guid("ad43ed5e-95cb-4a02-9dfb-0023042a0fa3"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 20.3342f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("45282dca-4815-4a7a-b0da-bf2c5988b738"),
                            CurrencyId = new Guid("821abd50-4fe7-489b-88ac-798db01056a4"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 56.84f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("09863bf5-3dd9-4e05-9707-56a50679a67c"),
                            CurrencyId = new Guid("0d0c13aa-21df-46a5-bf47-a1851c7f5edf"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.6356f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("486d265c-adb0-42ce-b0ea-4ee20ee535ec"),
                            CurrencyId = new Guid("3c3aabcf-f99d-4c5b-83a5-26ab411aec8e"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 97.6073f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("95d12f46-56cc-4fb3-afd3-fe7f80e1791c"),
                            CurrencyId = new Guid("53371f01-e292-4357-99b5-a67d6736aac5"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.412f,
                            UnitsNumber = 10000
                        },
                        new
                        {
                            Id = new Guid("e24bc51e-71c5-4769-81bc-d1cfdca62757"),
                            CurrencyId = new Guid("7df2afa7-c1c9-48d4-8e3c-dfbc7e7352ad"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 27.2741f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("3cc6cd61-8bbb-4acd-a412-95a475ec99d5"),
                            CurrencyId = new Guid("f0812695-d5a8-4bfb-91bf-85516f1c8812"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 100.3621f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("a703cc8c-61bb-463e-adc3-8d45ea059af1"),
                            CurrencyId = new Guid("9a0fcaf6-fd89-45c5-80c7-69667ecfc072"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 33.588f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("f984482c-9452-4ba4-a482-7879a5f7092d"),
                            CurrencyId = new Guid("9993e5ac-983c-41ce-9f1b-256146728aee"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 87.5909f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("5886de02-b515-48e9-b3fc-0003a278d75b"),
                            CurrencyId = new Guid("2ca026ca-1fb4-42d1-81f1-d9b1f28fa5a7"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 84.5209f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d05e54bb-c064-480a-ac16-c1d2afd74ca5"),
                            CurrencyId = new Guid("9bd76064-5329-4e9f-9099-539771740eff"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.6806f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("116f3345-49d3-4db8-921b-315cf6aa2ad2"),
                            CurrencyId = new Guid("9e0e348d-167d-4a5d-b110-182f96ddc6f6"),
                            Date = new DateTime(2020, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 72.9497f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("82ffdf35-1d07-4d78-9402-283151ad6731"),
                            CurrencyId = new Guid("11bbbf0e-148a-45ca-b329-6c95864f1945"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 77.2855f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f4bb4e0d-24e7-4633-bf96-08683d7cf93a"),
                            CurrencyId = new Guid("bf9242d7-1f47-462b-8609-02588ec24072"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 91.0732f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b82e96b3-7ce6-477c-8b4a-f1797688a5ec"),
                            CurrencyId = new Guid("a5d82e53-8aad-4978-a487-99f9368008c7"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 55.5837f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("05930cf4-2847-41aa-bd3d-711463ef0573"),
                            CurrencyId = new Guid("119c0396-3fd0-418b-8ba0-2dda0cd98891"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.4888f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d3417442-b152-47b0-95b7-ec434a0804e2"),
                            CurrencyId = new Guid("f0756449-1c50-40cc-ab55-b031e3ce9258"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 15.7597f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("e3203f08-1a6c-4acb-91af-4658271ec930"),
                            CurrencyId = new Guid("f1b53bf2-c36b-403a-b96e-3f70b90a6dbd"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 30.0815f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("3fd59dba-20e7-4251-83ec-9c3390fbc91b"),
                            CurrencyId = new Guid("91dac2a6-21be-49cf-a420-6e9d34e0c283"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.5856f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b604cca6-28f9-401d-a608-6aa775ffb56c"),
                            CurrencyId = new Guid("2401357a-e357-4d9b-8f58-6f0ef018df23"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 13.9714f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("395a8788-ff8a-4a23-a274-38d4f5b02964"),
                            CurrencyId = new Guid("565429b9-b082-43ae-a19f-962e9983a93d"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 25.3945f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("19c77875-9f28-4208-bf4a-57498eaafba0"),
                            CurrencyId = new Guid("0d02d2f7-9d33-4170-affc-e4f109ba77d3"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 67.4173f,
                            UnitsNumber = 1000
                        },
                        new
                        {
                            Id = new Guid("125907e0-2103-42e5-a2ae-920728f033ee"),
                            CurrencyId = new Guid("77018082-91cf-4237-a9f1-b8ea8e12d005"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 99.7219f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("64d6a1c8-b695-4f6c-a61d-418484b99edc"),
                            CurrencyId = new Guid("ead32013-ea79-4f7d-904f-74fe92e6a06d"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 12.2434f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("bc766e29-974b-4500-aea5-87f05e521ae5"),
                            CurrencyId = new Guid("966fa871-b850-48d0-b35a-01ac50ab133d"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 10.5398f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("f74780eb-5004-4846-abe4-2f9c01cf3703"),
                            CurrencyId = new Guid("75796b33-0cb2-465f-a2f9-b6b3174fdd6c"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.0052f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("045a182f-1b11-4889-9c1a-6de60a36d88e"),
                            CurrencyId = new Guid("8082345e-6d29-4f64-8137-e0e3e3338f6e"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 58.9156f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("c76bf645-219e-4092-8d81-2ce8d8890851"),
                            CurrencyId = new Guid("cb62c5e7-7d50-4095-989d-ec7bbddb103d"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 97.0388f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("a68b79ca-b15c-42ad-b692-d4c3b297e1ab"),
                            CurrencyId = new Guid("3b4eaabf-996d-4e3d-b3dc-3c47dab4601c"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 11.4672f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("1a1bb01e-207e-45d8-9fac-d8707e11f337"),
                            CurrencyId = new Guid("81b49f97-1846-4b89-a0af-1b9174f9c6ff"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.5962f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("e08a8c91-926c-4081-a31f-af81a1e24b9a"),
                            CurrencyId = new Guid("ba68a7cb-b46f-44a5-9048-de67b458c783"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.6942f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("8ec23d92-f90e-4d4d-99ae-d783ca2faf97"),
                            CurrencyId = new Guid("f5340578-affe-460e-a59a-cfbd87898a8e"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 22.1132f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("79c9adf0-13c4-431a-be2d-90017db1dac1"),
                            CurrencyId = new Guid("24ad525f-049c-4f4d-981e-d35bc1a34ad5"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 84.3452f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("ab96d22e-4761-4330-a823-289b64d3ebbb"),
                            CurrencyId = new Guid("ad43ed5e-95cb-4a02-9dfb-0023042a0fa3"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 20.3581f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("89a42a5f-213e-46a0-9479-46ad6129278a"),
                            CurrencyId = new Guid("821abd50-4fe7-489b-88ac-798db01056a4"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 56.8987f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("72256744-d7e8-4f66-b06e-9161802584e3"),
                            CurrencyId = new Guid("0d0c13aa-21df-46a5-bf47-a1851c7f5edf"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.7804f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("51a71771-fa07-4579-a9d6-4a7f585c3bed"),
                            CurrencyId = new Guid("3c3aabcf-f99d-4c5b-83a5-26ab411aec8e"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 97.7258f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("691c467b-3851-4124-8c5f-5d0433c95f79"),
                            CurrencyId = new Guid("53371f01-e292-4357-99b5-a67d6736aac5"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.6648f,
                            UnitsNumber = 10000
                        },
                        new
                        {
                            Id = new Guid("fd123d62-6bea-404b-aa62-2f6e6af865da"),
                            CurrencyId = new Guid("7df2afa7-c1c9-48d4-8e3c-dfbc7e7352ad"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 27.2902f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("2fc662b9-1a2b-48cd-a491-d1a39a456527"),
                            CurrencyId = new Guid("f0812695-d5a8-4bfb-91bf-85516f1c8812"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 100.7416f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("a976034b-f261-4c42-b87f-5babb91a7c23"),
                            CurrencyId = new Guid("9a0fcaf6-fd89-45c5-80c7-69667ecfc072"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 33.3185f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("647580dc-d5b9-4e8c-9f1b-9b777ae14963"),
                            CurrencyId = new Guid("9993e5ac-983c-41ce-9f1b-256146728aee"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 87.8494f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("979c7ee2-4e29-46fd-b0f5-124019530565"),
                            CurrencyId = new Guid("2ca026ca-1fb4-42d1-81f1-d9b1f28fa5a7"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 84.9105f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("e96f21f2-8742-4ab6-8f8f-fed3ac34bacb"),
                            CurrencyId = new Guid("9bd76064-5329-4e9f-9099-539771740eff"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.7889f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("b6c34c38-d197-4373-a21b-6606c1d8621e"),
                            CurrencyId = new Guid("9e0e348d-167d-4a5d-b110-182f96ddc6f6"),
                            Date = new DateTime(2020, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 73.2703f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("17bd5f15-d1c4-4e7e-bc3a-16722345fbc6"),
                            CurrencyId = new Guid("11bbbf0e-148a-45ca-b329-6c95864f1945"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 77.2759f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("d06af19d-414a-47e9-9c99-96a6b2ca082c"),
                            CurrencyId = new Guid("bf9242d7-1f47-462b-8609-02588ec24072"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 90.7065f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("c8a64de0-c959-4910-9904-66d0515427d9"),
                            CurrencyId = new Guid("a5d82e53-8aad-4978-a487-99f9368008c7"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 55.4609f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("144731c5-25cb-4cfb-bde3-e4ce9428f8db"),
                            CurrencyId = new Guid("119c0396-3fd0-418b-8ba0-2dda0cd98891"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.4832f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("60a76d9e-5794-4e3a-837e-c23ce063585f"),
                            CurrencyId = new Guid("f0756449-1c50-40cc-ab55-b031e3ce9258"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 15.7545f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("76b903a6-fcc6-46ed-80df-c10708d0fed9"),
                            CurrencyId = new Guid("f1b53bf2-c36b-403a-b96e-3f70b90a6dbd"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 30.0439f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("62c49935-cde6-4cd4-9b4a-dd26a450c302"),
                            CurrencyId = new Guid("91dac2a6-21be-49cf-a420-6e9d34e0c283"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.4036f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("755eeef9-db72-43af-9057-25a337c2b071"),
                            CurrencyId = new Guid("2401357a-e357-4d9b-8f58-6f0ef018df23"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 13.8733f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("6bb52956-afbb-4495-9f76-67aaca79f50b"),
                            CurrencyId = new Guid("565429b9-b082-43ae-a19f-962e9983a93d"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 24.9293f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("6a91a2b0-6e81-4891-96bd-d678676d055b"),
                            CurrencyId = new Guid("0d02d2f7-9d33-4170-affc-e4f109ba77d3"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 67.4934f,
                            UnitsNumber = 1000
                        },
                        new
                        {
                            Id = new Guid("72b7cc2e-3786-4851-bbf8-9bbaa2cc29b9"),
                            CurrencyId = new Guid("77018082-91cf-4237-a9f1-b8ea8e12d005"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 99.7096f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("93d5e7f6-dbba-47c4-b98f-8279b2489491"),
                            CurrencyId = new Guid("ead32013-ea79-4f7d-904f-74fe92e6a06d"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 12.1946f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f8fe49c4-ae2e-4217-bc8b-798e6eef4759"),
                            CurrencyId = new Guid("966fa871-b850-48d0-b35a-01ac50ab133d"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 10.5462f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("d3019cc7-c382-4562-948f-c24ad20ce2a3"),
                            CurrencyId = new Guid("75796b33-0cb2-465f-a2f9-b6b3174fdd6c"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 17.9988f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("e4ec08d9-2ecb-423f-b787-9548925a0bc1"),
                            CurrencyId = new Guid("8082345e-6d29-4f64-8137-e0e3e3338f6e"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 58.8679f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b95c0267-4401-4d74-9438-1e7e5937f634"),
                            CurrencyId = new Guid("cb62c5e7-7d50-4095-989d-ec7bbddb103d"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 96.9766f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("8192bf2e-0e08-4540-a000-8a4a7b2e9612"),
                            CurrencyId = new Guid("3b4eaabf-996d-4e3d-b3dc-3c47dab4601c"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 11.4675f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b0b01503-e522-41d7-891f-5982a0f9ce99"),
                            CurrencyId = new Guid("81b49f97-1846-4b89-a0af-1b9174f9c6ff"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.6444f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("5d7260aa-096a-4ab6-bd88-8c9ce6706d2b"),
                            CurrencyId = new Guid("ba68a7cb-b46f-44a5-9048-de67b458c783"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.6153f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("561af24e-e546-4650-ba72-9f64be8cce85"),
                            CurrencyId = new Guid("f5340578-affe-460e-a59a-cfbd87898a8e"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 22.1104f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("2b01eafd-5940-4bd3-8f81-1ca32a5a7746"),
                            CurrencyId = new Guid("24ad525f-049c-4f4d-981e-d35bc1a34ad5"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 83.6944f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("8760d9ea-c157-47f2-a82a-ab7da6e601f2"),
                            CurrencyId = new Guid("ad43ed5e-95cb-4a02-9dfb-0023042a0fa3"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 20.2039f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("9dbc3f41-82fb-4699-8260-4492b52a6cac"),
                            CurrencyId = new Guid("821abd50-4fe7-489b-88ac-798db01056a4"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 56.9f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("1b22bc7e-13e0-471c-8d86-d3922871b634"),
                            CurrencyId = new Guid("0d0c13aa-21df-46a5-bf47-a1851c7f5edf"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.7711f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("e9ca9282-2b73-4aed-869c-b1c81fca47c4"),
                            CurrencyId = new Guid("3c3aabcf-f99d-4c5b-83a5-26ab411aec8e"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 97.2305f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("efcb649c-80d8-48a1-b3dc-0c6d6ab205c6"),
                            CurrencyId = new Guid("53371f01-e292-4357-99b5-a67d6736aac5"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.6555f,
                            UnitsNumber = 10000
                        },
                        new
                        {
                            Id = new Guid("7a4672ea-553b-4983-916f-36c89c63c911"),
                            CurrencyId = new Guid("7df2afa7-c1c9-48d4-8e3c-dfbc7e7352ad"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 27.2674f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("0b684191-0f82-4d76-be90-d5e671089410"),
                            CurrencyId = new Guid("f0812695-d5a8-4bfb-91bf-85516f1c8812"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 99.6859f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("659bbacb-75f9-43f5-a868-bfee5d87d34d"),
                            CurrencyId = new Guid("9a0fcaf6-fd89-45c5-80c7-69667ecfc072"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 33.1116f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("cbd4027d-be66-46cb-b367-875f2f38e03e"),
                            CurrencyId = new Guid("9993e5ac-983c-41ce-9f1b-256146728aee"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 87.676f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("0da42dda-ba56-4fb8-bda6-9c1124f7f37a"),
                            CurrencyId = new Guid("2ca026ca-1fb4-42d1-81f1-d9b1f28fa5a7"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 84.5654f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("84d539f6-d1f4-4a49-9df5-6c2df22ee9b0"),
                            CurrencyId = new Guid("9bd76064-5329-4e9f-9099-539771740eff"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.7905f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("a4df6d58-799e-438a-bd03-dddbbfd2e7f6"),
                            CurrencyId = new Guid("9e0e348d-167d-4a5d-b110-182f96ddc6f6"),
                            Date = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 73.3133f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("67e68f32-84c8-49c4-8faa-648ec30027e6"),
                            CurrencyId = new Guid("11bbbf0e-148a-45ca-b329-6c95864f1945"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 77.9461f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("aac865f1-0f01-4281-a309-6a686d5864fd"),
                            CurrencyId = new Guid("bf9242d7-1f47-462b-8609-02588ec24072"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 91.4542f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("36cc37cd-f425-43b4-bb92-2982c1e5c84a"),
                            CurrencyId = new Guid("a5d82e53-8aad-4978-a487-99f9368008c7"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 55.2248f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("e88a43ec-ceb6-48c8-972f-5cea4972d521"),
                            CurrencyId = new Guid("119c0396-3fd0-418b-8ba0-2dda0cd98891"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.8776f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b7916e04-4742-43d8-bd00-b889ebedfc64"),
                            CurrencyId = new Guid("f0756449-1c50-40cc-ab55-b031e3ce9258"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 15.864f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("18cd19b7-f456-4f05-af3c-a6014d3e31e8"),
                            CurrencyId = new Guid("f1b53bf2-c36b-403a-b96e-3f70b90a6dbd"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 30.2833f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("cd9db85f-de41-4f90-8c18-3f682abd44e2"),
                            CurrencyId = new Guid("91dac2a6-21be-49cf-a420-6e9d34e0c283"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.6939f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("b55cfe42-2881-4c9f-b540-eab27bca5d81"),
                            CurrencyId = new Guid("2401357a-e357-4d9b-8f58-6f0ef018df23"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 13.9384f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("1980512b-eeaa-4000-8898-0760eac5536a"),
                            CurrencyId = new Guid("565429b9-b082-43ae-a19f-962e9983a93d"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 24.9992f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("bbcd1ea9-0820-498f-a16b-f964669542a4"),
                            CurrencyId = new Guid("0d02d2f7-9d33-4170-affc-e4f109ba77d3"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 68.0033f,
                            UnitsNumber = 1000
                        },
                        new
                        {
                            Id = new Guid("68101c69-c4ec-4a19-94c2-0c2dfc196d29"),
                            CurrencyId = new Guid("77018082-91cf-4237-a9f1-b8ea8e12d005"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 10.0574f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("520c2259-2527-4bb2-86fc-0786960660d4"),
                            CurrencyId = new Guid("ead32013-ea79-4f7d-904f-74fe92e6a06d"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 12.2698f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("15f95a1b-dd55-466f-9445-c83626346651"),
                            CurrencyId = new Guid("966fa871-b850-48d0-b35a-01ac50ab133d"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 10.6223f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("5ccbd855-ce37-4432-a1e9-84e7cac59c68"),
                            CurrencyId = new Guid("75796b33-0cb2-465f-a2f9-b6b3174fdd6c"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.1824f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("829d02a5-ddc5-4cd0-934e-d2ede400b5e3"),
                            CurrencyId = new Guid("8082345e-6d29-4f64-8137-e0e3e3338f6e"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 59.1576f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("139e3230-f20b-43ee-8579-96c863bd2216"),
                            CurrencyId = new Guid("cb62c5e7-7d50-4095-989d-ec7bbddb103d"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 97.7889f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("e7decbd5-d23f-4ff7-beac-47effd870ca3"),
                            CurrencyId = new Guid("3b4eaabf-996d-4e3d-b3dc-3c47dab4601c"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 11.5803f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("5fd76a42-6374-4feb-a202-f9637a8d760a"),
                            CurrencyId = new Guid("81b49f97-1846-4b89-a0af-1b9174f9c6ff"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.9859f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("da1524ed-80b9-4e41-831a-61f9c749bda2"),
                            CurrencyId = new Guid("ba68a7cb-b46f-44a5-9048-de67b458c783"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.7267f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("1eae62d1-21c3-4dfb-b74f-c5dc567804af"),
                            CurrencyId = new Guid("f5340578-affe-460e-a59a-cfbd87898a8e"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 22.3022f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("491cfe8e-d7e3-4129-8de1-06345bf5abc6"),
                            CurrencyId = new Guid("24ad525f-049c-4f4d-981e-d35bc1a34ad5"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 83.3666f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("0036cda9-6b2f-4782-b5c0-3881b2997ea8"),
                            CurrencyId = new Guid("ad43ed5e-95cb-4a02-9dfb-0023042a0fa3"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 20.0778f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("03369b70-e0a6-464c-acd3-d9e5b0d58340"),
                            CurrencyId = new Guid("821abd50-4fe7-489b-88ac-798db01056a4"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 57.326f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("09ef7b7d-c85e-44a2-9338-60c81680207e"),
                            CurrencyId = new Guid("0d0c13aa-21df-46a5-bf47-a1851c7f5edf"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 75.4195f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("93b232cc-fd8d-4b4f-8445-d1d330b558ea"),
                            CurrencyId = new Guid("3c3aabcf-f99d-4c5b-83a5-26ab411aec8e"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 98.2122f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("04d001b2-6f54-4207-80cf-4458b5469005"),
                            CurrencyId = new Guid("53371f01-e292-4357-99b5-a67d6736aac5"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 75.303f,
                            UnitsNumber = 10000
                        },
                        new
                        {
                            Id = new Guid("1871816c-86d7-4747-aa62-918630278c69"),
                            CurrencyId = new Guid("7df2afa7-c1c9-48d4-8e3c-dfbc7e7352ad"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 27.5049f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("3c102c70-beea-474e-8d20-1363d6cf97ef"),
                            CurrencyId = new Guid("f0812695-d5a8-4bfb-91bf-85516f1c8812"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 101.1584f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("a6eaf0fe-0bab-4139-a953-25bbced8a783"),
                            CurrencyId = new Guid("9a0fcaf6-fd89-45c5-80c7-69667ecfc072"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 33.4676f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("1898c167-6512-45bc-8e2b-5f58de3bd3c0"),
                            CurrencyId = new Guid("9993e5ac-983c-41ce-9f1b-256146728aee"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 87.8009f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("7794fa44-7853-4166-8832-31d2e179443f"),
                            CurrencyId = new Guid("2ca026ca-1fb4-42d1-81f1-d9b1f28fa5a7"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 85.2429f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("e332b0a5-823b-472d-b996-25c0da34f874"),
                            CurrencyId = new Guid("9bd76064-5329-4e9f-9099-539771740eff"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.7822f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("0051e5b9-e39f-44e4-838e-fccdde4a15e2"),
                            CurrencyId = new Guid("9e0e348d-167d-4a5d-b110-182f96ddc6f6"),
                            Date = new DateTime(2020, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.0616f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("66bba7da-df30-438c-b0e9-db961de29f8a"),
                            CurrencyId = new Guid("11bbbf0e-148a-45ca-b329-6c95864f1945"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 77.9644f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("192f34f9-969e-4fd9-bdd5-3f992d144341"),
                            CurrencyId = new Guid("bf9242d7-1f47-462b-8609-02588ec24072"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 91.3041f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("369eff7a-dd2f-4698-9f67-3e98342e930a"),
                            CurrencyId = new Guid("a5d82e53-8aad-4978-a487-99f9368008c7"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 55.2534f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("4fa58cb4-0771-4ba7-8e28-7bcff1bf34ab"),
                            CurrencyId = new Guid("119c0396-3fd0-418b-8ba0-2dda0cd98891"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.8884f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("8032d901-bd3a-4378-ac82-58e99350a9f8"),
                            CurrencyId = new Guid("f0756449-1c50-40cc-ab55-b031e3ce9258"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 15.8567f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("4e8370e5-6d94-4c36-b1e2-1d03c6f4ed40"),
                            CurrencyId = new Guid("f1b53bf2-c36b-403a-b96e-3f70b90a6dbd"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 30.3234f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("2f485e6e-6c4d-4e6f-8977-1699409f46fb"),
                            CurrencyId = new Guid("91dac2a6-21be-49cf-a420-6e9d34e0c283"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 46.6965f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("5516ddf0-9e4f-4178-ab3c-6d1929245a72"),
                            CurrencyId = new Guid("2401357a-e357-4d9b-8f58-6f0ef018df23"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 13.8912f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("359f7d86-567e-4dc9-94e5-391ee5606724"),
                            CurrencyId = new Guid("565429b9-b082-43ae-a19f-962e9983a93d"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 25.0295f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("2a15d933-6ca0-48c6-913d-e9504d3dab74"),
                            CurrencyId = new Guid("0d02d2f7-9d33-4170-affc-e4f109ba77d3"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 68.0903f,
                            UnitsNumber = 1000
                        },
                        new
                        {
                            Id = new Guid("bf34ce28-7a04-495b-bd68-66946d79a4b0"),
                            CurrencyId = new Guid("77018082-91cf-4237-a9f1-b8ea8e12d005"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 10.0598f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("b85e572d-296b-4f70-ba3f-717e36052b85"),
                            CurrencyId = new Guid("ead32013-ea79-4f7d-904f-74fe92e6a06d"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 12.2707f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("3e0615aa-6d37-41c4-b950-858031a878ef"),
                            CurrencyId = new Guid("966fa871-b850-48d0-b35a-01ac50ab133d"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 10.6291f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("ee8b73bf-02a1-4180-8c49-c5181d4fa79d"),
                            CurrencyId = new Guid("75796b33-0cb2-465f-a2f9-b6b3174fdd6c"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.1697f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("0c304841-1ad4-4986-af94-280254710feb"),
                            CurrencyId = new Guid("8082345e-6d29-4f64-8137-e0e3e3338f6e"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 59.0237f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("a77fe535-ed35-466a-9ce2-1d899cf5bd2b"),
                            CurrencyId = new Guid("cb62c5e7-7d50-4095-989d-ec7bbddb103d"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 97.4555f,
                            UnitsNumber = 100
                        },
                        new
                        {
                            Id = new Guid("a52594c9-ff85-48a8-b9a7-f2e013370bec"),
                            CurrencyId = new Guid("3b4eaabf-996d-4e3d-b3dc-3c47dab4601c"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 11.6398f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("e876fe0b-6b3e-44a7-8c47-f2091e3cf5f2"),
                            CurrencyId = new Guid("81b49f97-1846-4b89-a0af-1b9174f9c6ff"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 45.8749f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("f2b9db5d-6040-4042-b0be-253e4e13fd18"),
                            CurrencyId = new Guid("ba68a7cb-b46f-44a5-9048-de67b458c783"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 18.7302f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("776ea683-bc75-428d-8fa2-0447dfd20977"),
                            CurrencyId = new Guid("f5340578-affe-460e-a59a-cfbd87898a8e"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 22.3074f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("9819678c-f949-435d-b8f0-a9863563e354"),
                            CurrencyId = new Guid("24ad525f-049c-4f4d-981e-d35bc1a34ad5"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 83.2846f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("e012751f-4d80-4774-8d44-4ade94f33229"),
                            CurrencyId = new Guid("ad43ed5e-95cb-4a02-9dfb-0023042a0fa3"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 20.0345f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("c8b0b3ef-ab16-4851-b99e-cec43d2460b3"),
                            CurrencyId = new Guid("821abd50-4fe7-489b-88ac-798db01056a4"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 57.3943f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("4752e94e-14f7-4603-a22c-1fc025f3b6f1"),
                            CurrencyId = new Guid("0d0c13aa-21df-46a5-bf47-a1851c7f5edf"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 75.4373f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("9c35f0e1-0ded-4f92-b006-ca085d91fcca"),
                            CurrencyId = new Guid("3c3aabcf-f99d-4c5b-83a5-26ab411aec8e"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 98.3468f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("7581c5e4-f3e7-4648-ba51-80ccd2461135"),
                            CurrencyId = new Guid("53371f01-e292-4357-99b5-a67d6736aac5"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 75.3206f,
                            UnitsNumber = 10000
                        },
                        new
                        {
                            Id = new Guid("b1914048-47df-423c-99b3-9f129075e5f2"),
                            CurrencyId = new Guid("7df2afa7-c1c9-48d4-8e3c-dfbc7e7352ad"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 27.4958f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("1967f7c1-9655-4bd0-a366-2e1742506d79"),
                            CurrencyId = new Guid("f0812695-d5a8-4bfb-91bf-85516f1c8812"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 100.8625f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("2dd7c62a-2d5b-46b4-8970-55255992adf7"),
                            CurrencyId = new Guid("9a0fcaf6-fd89-45c5-80c7-69667ecfc072"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 33.4324f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("edea4897-c6e7-4a15-923e-2de2352cbf31"),
                            CurrencyId = new Guid("9993e5ac-983c-41ce-9f1b-256146728aee"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 88.1541f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("1fb9b057-2ccb-46e4-9c94-b7006816345c"),
                            CurrencyId = new Guid("2ca026ca-1fb4-42d1-81f1-d9b1f28fa5a7"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 85.2163f,
                            UnitsNumber = 1
                        },
                        new
                        {
                            Id = new Guid("f1069d09-db3d-4bbd-8d49-f7d4d44d2ce4"),
                            CurrencyId = new Guid("9bd76064-5329-4e9f-9099-539771740eff"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 47.0629f,
                            UnitsNumber = 10
                        },
                        new
                        {
                            Id = new Guid("876532f8-88a7-4cbb-875c-8d552090bc56"),
                            CurrencyId = new Guid("9e0e348d-167d-4a5d-b110-182f96ddc6f6"),
                            Date = new DateTime(2020, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rate = 74.0895f,
                            UnitsNumber = 100
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ExchangeRate", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Currency", null)
                        .WithMany("ExchangeRates")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
